name: Build

env:
  QUAY_BASE: quay.io/miabbott/fcos-image-builder

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: "Build container image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push container images
        run: |
          set -xeuo pipefail
          mkdir -p ~/.docker
          cat > ~/.docker/config.json <<EOF
          ${{ secrets.QUAY_AUTH }}
          EOF
          head=$(git rev-parse HEAD)
          podman build -t "${{ env.QUAY_BASE}}:$head" -f Containerfile .
          podman push "${{ env.QUAY_BASE}}:$head"
          podman tag "${{ env.QUAY_BASE}}:$head" "${{ env.QUAY_BASE }}:latest"
          podman push "${{ env.QUAY_BASE }}:latest"
          rm ~/.docker/config.json
          echo "head=${head}" >> $GITHUB_ENV
      - name: Update README and Containerfile
        run: |
          # This is load-bearing: GitHub will disable the job if the repo
          # doesn't stay active.  Do not enable branch protection for main;
          # it'll break this.
          set -xeuo pipefail
          git config user.name 'Micah Abbott'
          git config user.email miabbott@redhat.com
          sed -i "s/updated-.*-green/updated-$(date +%Y--%m--%d)-green/" README.md
          sed -i "s/commit:.*/commit: ${head}/" Containerfile
          git add README.md Containerfile
          if git diff --quiet --staged --exit-code; then
            echo "README.md already up to date"
            exit 0
          fi
          git commit -m "README.md: update build date"
          git push
